/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AduioRecord: typeof import('./components/views/video/cpns/aduioRecord/AduioRecord.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Home: typeof import('./components/views/home/home.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MyVideo: typeof import('./components/views/video/cpns/myVideo/MyVideo.vue')['default']
    RightContent: typeof import('./components/views/video/cpns/rightContent/RightContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitPane: typeof import('./components/layouts/SplitPane.vue')['default']
    SubTitle: typeof import('./components/views/video/cpns/subTitle/subTitle.vue')['default']
    Video: typeof import('./components/views/video/video.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
